### ISSUE TITLE
Players can use beds whilst in an Exosuit

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10483]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Players wearing the Exosuit can sleep in beds. Not only is this wildly impractical, it also looks wrong due to the sheer mass of the Exosuit sprite. Half of the suit is not on the bed mattress whilst the front of the Exosuit goes _through_ the top bunk. The Exosuit doesn't fit in the bed whatsoever.

![image](https://user-images.githubusercontent.com/105495756/202923729-e8d2908b-d7fa-4f7d-9b26-197782ccf816.png)

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57aea10f75b5449b96e19bfe60c557ac9ae3e8cf

**Comment by Wheatley1001** [comment]
![image](https://user-images.githubusercontent.com/105495756/204042455-93f022ce-e20b-49a3-9949-a7dd33bb3c95.png)
![image](https://user-images.githubusercontent.com/105495756/204042464-a4993004-2096-4293-9249-47745708e7fd.png)
Issue still present in 100.6.0.0.

**Comment by Regalis11** [comment]
Could not reproduce. I suspect this happens in older test branch saves, considering the upgrade elements that add the restriction to the beds are only configured to upgrade versions prior to 0.20.8.0.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by DrBruhman** [comment]
legacy bunk (also wrecked version) dose not contains required item line (can be used with exosuit)
![изображение](https://github.com/user-attachments/assets/3aae1e9a-a5cc-4a2b-a259-7ca9f29d760b)

"new" bunks as example
![изображение](https://github.com/user-attachments/assets/65f76d39-8580-4878-9eb4-07e63659dedc)
