### ISSUE TITLE
Issues with large creatures/abyss creatures dropping loot on death.

### ISSUE THREAD

**Issue by PokkeTigrex** [Regalis11/Barotrauma#10546]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

So with the new unstable patch, a handful of special loot items were added to large creatures and abyss creatures. The problem comes at how looting them now handles. Instead of needing to access their inventory, they now drop it from their inventory. This is a problem, as these items can be quite small and has no indicator on where they have went, especially the items that has no buoyancy. These items can easily get lost during combat and what not as they are no longer tied to the body anymore, will sink somewhere, or get hidden behind the large abyss creature body. 

I believe that accessing their inventories is still a much better approach, even with large abyss creatures as the items remain on the body, not where ever the hell it got launched to after being dropped. A method of making finding that grab point could help, perhaps a small light glint to indicate the location of the valuables on the corpse?

As for other issues, killing an large monster like the moloch at the same time as spawning them (without closing console) will let them retain their items in the inventory, but if you let them spawn and close console then kill them afterwards, they will drop the items. Also, for some reason charybdis drops scrap and ballistic fiber...?

### Reproduction steps

Try to find all moloch bones and mineral/shell drops after being rammed across the map against 5 molochs, good luck :)

### Bug prevalence

Happens every time I play

### Version

0.20.8.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
Images of this in action (it is also important to add that the Moloch Bones float in water. They just kinda sit there):

![image](https://user-images.githubusercontent.com/105495756/204067455-1966ad04-dd22-4d0d-be2b-01c5abd24f8a.png)
![image](https://user-images.githubusercontent.com/105495756/204067514-487309a9-88b3-41c3-8d76-6a4bebe41e37.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c557503dee79e359ff6cd2440a6e7d2d10bb651a by making large monsters easier to grab and https://github.com/Regalis11/Barotrauma-development/commit/9ba4fff2534cc6a238afce974792193a61e8306e by making the creatures not drop the loot on death.

**Comment by Rokvach** [comment]
You can keep the creature grabbed even though they aren't anywhere near your character, for example Endworms fall quite fast while dead so if you grab one and wait for a bit you can see that you still have access to the creatures inventory even though it isn't anywhere near you anymore.

There is couple ways to address this.
A. Drag the player character with the creature if they are grabbing it (more fun)
B. Ungrab if the creatures grab range is certain distance away from the player character

**Comment by Rokvach** [comment]
I didn't notice any issues with looting large creatures after the fix. Working correctly, closing.

**Comment by Wheatley1002** [comment]
Unsure if this commit made it to 100.13.0.0 but the issue persisted in that build. Will check in 100.14.0.0 since that combined the last two unstable updates to that branch.
