### ISSUE TITLE
Small text bug during the medic tutorial

### ISSUE THREAD

**Issue by Calcolan-Was-Somehow-Taken** [Regalis11/Barotrauma#10751]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![602960_screenshots_20221217041939_1](https://user-images.githubusercontent.com/120821337/208255576-76242d53-76db-4110-a83e-dedd27b4160a.jpg)

Small text bug which I have only encountered twice during the medic tutorial (I only did the tutorial twice but I think it would keep happening)

### Reproduction steps

Start the tutorial
Pick medic
Continue through the tutorial until you use the fabricator

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Also mentioned in the private issue ticket: Regalis11/Barotrauma-development#3822.

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/59edccc35745efb9ee797fbf6a49789b02c73c16

**Comment by ganaern** [comment]
Same issue in version 0.20.16.1
Able to reproduce every time
Occurs just after creating Naloxone in the medic role tutorial
no other impact seen other than the missing text.
![Dialog Bug - Medic - Role Training](https://user-images.githubusercontent.com/24447895/211637936-34286293-ae28-4195-a042-50d96cf1e57d.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by akariaon** [comment]
This issue is still present in the game. Encountered it 4 days ago

**Comment by JeroonBosch** [comment]
Have you updated to the latest patch?
