### ISSUE TITLE
Propeller pos

### ISSUE THREAD

**Issue by rav2n** [Regalis11/Barotrauma#1840]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The propeller position of the inverted engine on the Y axis is reset to default sets

**Steps To Reproduce**
Turn the engine in editor and change the position of the propeller. Save submarine. Load submarine in editor or in game. Check propeller position.

**Version**
v0.9.4.0 

**Additional information**
Not the most important problem, but before the patch everything worked. =(

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/87a9a11f73bc0716086a648bd3e41ec303a5c598 (private repo)

**Comment by itchyOwl** [comment]
I was not able to reproduce the issue in the first place, although I don't doubt there is one. Could @ezjamsen confirm that this is fixed?

**Comment by rav2n** [comment]
![image](https://user-images.githubusercontent.com/29980468/68687130-cefd9e80-057d-11ea-8513-f22a7f3d0eaf.png)

**Comment by itchyOwl** [comment]
Thanks for the clarification. I didn't notice it, because I was keeping my eye on the "Propeller Pos" property instead of the red rectangle indicating the final position.

Confirmed that the issue is present in 0.9.4.0 and that it is partially fixed in Regalis11/Barotrauma-development@87a9a11. I noticed that the fix does not correct the incorrect values that were saved _before_ the fix was made. It's a minor issue, however.

**Comment by danielasteljoki** [comment]
Tested, new propeller position was saved correctly.

**Comment by itchyOwl** [comment]
Moved to "Done".

**Comment by rav2n** [comment]
Oh good.
