### ISSUE TITLE
[Issue] [Networking] [0.9.5.1] Peers will occasionally walk in place while using periscope

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1886]
When you use a periscope, to others it may sometimes appear that you are walking in place... despite you obviously not doing this. Your legs move in a walk cycle while your head is tethered to the usual persicope limbposition. Will look into reproducing further.

**Comment by hubismal** [comment]
To clarify, this is pretty hard to reproduce. I'm beginning to think it's desync related, but either way it's a graphical bug that shouldn't happen.

**Comment by Regalis11** [comment]
This can be reproduced pretty reliably by doing the following:
1. Use high simulated latency
2. Order a bot to man a periscope
3. Select the periscope just before the bot selects it (the timing has to be pretty precise: the bot needs to select the periscope first server-side while you need to select it first at your side).

https://github.com/Regalis11/Barotrauma-development/commit/a3cb7c6fa72cf4c23122b4f844c37de6d2561a8e (private repo) should fix this.

**Comment by Rokvach** [comment]
Tested, still an issue. During a testing round I ordered all the bots to the gunners and we bumped the sub head first to a wall causing the bots to lose their grip of the periscope and start to walk in place. @Regalis11

**Comment by Regalis11** [comment]
Another attempt to fix this in https://github.com/Regalis11/Barotrauma-development/commit/b8b6bf2 (private repo)

**Comment by Rokvach** [comment]
Tested, working correctly now. Moving to Done.

**Comment by Rokvach** [comment]
Nevermind, spotted it right after I moved this ticket, the bots will still walk in place but this time face the correct direction at least

https://streamable.com/ue2lb

**Comment by Regalis11** [comment]
Wasn't able to reproduce that. If it happens again, could you take a clip with debudraw on? Or if you manage to figure out a way to make it occur again, please let us know.

**Comment by Regalis11** [comment]
Closing this as there are no known steps to reproduce the issue anymore.
