### ISSUE TITLE
[0.9.707] Campaign(?) - Cannot start round after playing through one round

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2257]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
After playing a round of campaign, the next round will not start. Will loop on this error:
![Capture](https://user-images.githubusercontent.com/5086682/74279508-0993e600-4ce9-11ea-8aa8-938b0c493eb1.PNG)

**Version**
0.9.707

**Additional Informations**
Unsure if other modes are affected.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/084f0b0a750067010178fb7073e3247e26282e09

**Comment by Rokvach** [comment]
Was reverted, waiting for a merge.

**Comment by Regalis11** [comment]
This is not a blocker for #2258, the issues are unrelated.

**Comment by Rokvach** [comment]
I added it because they came from the same branch as a reminder to check it with the new startround fix

**Comment by Rokvach** [comment]
This is still an issue when trying to start a second round in Campaign

![startroundissue.jpg](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/57a8d241-1a5e-4c83-bec2-67c30a3124bc)

**Comment by Rokvach** [comment]
Couldn't reproduce this issue after the latest fixes. Closing.
