### ISSUE TITLE
[Unstable] Can't run dedicated server

### ISSUE THREAD

**Issue by FamiliarBreakfast** [Regalis11/Barotrauma#2310]
First of all, how am I supposed to run the official dedicated server app?
I can't figure it out so I tried to use the built in function by running ./DedicatedServer from the game folder, but that just gives this error:
```
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__46 threw an exception: InitGameServer returned false (0,27636,27015,27016,2,"1.0.0.0")
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in /home/ff/Documents/Barotrauma-development/Libraries/Facepunch.Steamworks/SteamServer.cs:line 97                                                                                       
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in /home/ff/Documents/Barotrauma-development/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 26                                                                        
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext() in /home/ff/Documents/Barotrauma-development/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 196                                                                               
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/ff/Documents/Barotrauma-development/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 211   
```

**Comment by niktwenty3** [comment]
Tried running the dedicated server after the latest update and got the same message. Tried various things but haven't gotten it working yet. @Jlobblet on Discord managed to get it working but we haven't figured out yet why or exactly how. Check the conversation on #baro-support with him and I (@WickedNik).

**Comment by niktwenty3** [comment]
Did some more digging and here is some extra information. 

The first parameter of this error `InitGameServer returned false (0,27636,27015,27016,2,"1.0.0.0")` is supposed to be the IP address. `0` is obviously not an IP address. 

The error is thrown on `Libraries/Facepunch.Steamworks/SteamServer.cs`. Specifically within the [init function](https://github.com/Regalis11/Barotrauma/blob/master/Libraries/Facepunch.Steamworks/SteamServer.cs#L75). 

This is a sample of the relevant code.

```
uint ipaddress = 0; // Any Port

			if ( init.SteamPort == 0 )
				init = init.WithRandomSteamPort();

			if ( init.IpAddress != null )
				ipaddress = Utility.IpToInt32( init.IpAddress );

			System.Environment.SetEnvironmentVariable( "SteamAppId", appid.ToString() );
			System.Environment.SetEnvironmentVariable( "SteamGameId", appid.ToString() );
			var secure = (int)(init.Secure ? 3 : 2);

			//
			// Get other interfaces
			//
			if ( !SteamInternal.GameServer_Init( ipaddress, init.SteamPort, init.GamePort, init.QueryPort, secure, init.VersionString ) )
			{
				throw new System.Exception( $"InitGameServer returned false ({ipaddress},{init.SteamPort},{init.GamePort},{init.QueryPort},{secure},\"{init.VersionString}\")" );
			}
```

I'm guessing that for some reason the IP can't be selected. Or maybe it has issues when more than 1 IP are present. Anyways, I mainly do frontend and some backend for web so not really qualified to fix this :P

**Comment by thehollowedone** [comment]
I am having the issue above on an OVH Server running Ubuntu. 
I am using LinuxGSM and on start I am warned I have multiple ips, this may be another source to the problem.

**Comment by Jlobblet** [comment]
_Preface: I'm running `Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-1060-aws x86_64)` with 8GB of RAM. I've run `sudo dpkg --add-architecture i386` to add repositories necessary to install some dependencies._

I can now reproducibly get the server to boot from a clean install.

**Instructions for getting to boot**
"Using" steamcmd:
_**NB**: If you installed steamcmd manually, the server root directory listed will probably be different to the tune of `~/Steam/steamapps/common/Barotrauma\ Dedicated\ Server/`._
1.  Run `steamcmd +login anonymous +app_update 1026340`. If you installed steamcmd manually, use `./steamcmd.sh +login anonymous +app_update 1026340` instead. Expected final output should be `Success! App '1026340' fully installed.`
2.  Make sure that the directory `~/.steam/sdk64/` exists, i.e. `mkdir ~/.steam/sdk64`.
3.  Create a symlink as follows: `ln -s ~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/DedicatedServer ~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/DedicatedServer.exe`. This is because the executable was moved to just be called `DedicatedServer`. Check it was linked (should be light blue when you `ls`). _Note: this step is probably superfluous at the moment, since we end up running the server directly, but still fixes one of the steamcmd errors. Probably ought to be done anyway._
4.  Create a symlink as follows: `ln -s ~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/linux64/steamclient.so ~/.steam/sdk64/steamclient.so`, and check it works (should be light blue when you `ls`).
5.  Create a file in the root directory of the server called `steam_appid.txt` (`~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/steam_appid.txt`) with content `602960`, Barotrauma's Steam App ID (shocking, I know).
6.  Run the server directly, i.e. `cd ~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/` and then `./DedicatedServer`. The server should boot, with final output `Server started`. To get it to run in the background, use `screen` or something.

Using LinuxGSM:
_**NB**: I created the folder `~/linuxgsm/` to dump all the files in. Your installation may vary! I will cover a completely fresh install here._
1.  `From ~/linuxgsm/`, run `wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh btserver`, followed by `./btserver install` to install the server. _If you're just updating, run `./btserver update`_
2.  Create the symlink as follows: `ln -s ~/linuxgsm/serverfiles/DedicatedServer ~/linuxgsm/serverfiles/DedicatedServer.exe`. 
3.  Make sure the directory `~/linuxgsm/serverfiles/lib64/` exists, i.e. `mkdir ~/linuxgsm/serverfiles/lib64/`.
4.  Create the symlink as follows: `ln -s ~/linuxgsm/steamcmd/linux64/steamclient.so ~/linuxgsm/serverfiles/lib64/steamclient.so`.
5.  Create the file `~/linusgsm/serverfiles/steam_appid.txt` with content `602960`.
6.  From `~/linguxgsm/`, run `./btserver start` to start the server. To confirm it's working, use `./btserver console`. Final output should be `Server started`.

I've been able to get the Dedicated Server to boot using both of these methods. Feel free to get in touch with me here or on Discord (Jlobblet#0536) and I'll be happy to help you get it working.

**Comment by niktwenty3** [comment]
Can confirm that with @Jlobblet 's guide I got it working. Key points here being adding the symlink for `~/.steam/sdk64/steamclient.so` and `steam_appid.txt` in the server directory. If I remove the txt file the server get's the error initially posted.

**Comment by Jlobblet** [comment]
> 
> 
> Can confirm that with @Jlobblet 's guide I got it working. Key points here being adding the symlink for `~/.steam/sdk64/steamclient.so` and `steam_appid.txt` in the server directory. If I remove the txt file the server get's the error initially posted.

I can only presume the file is needed for one of these two lines.
https://github.com/Regalis11/Barotrauma/blob/3e99a49383aad941a29a86e51e022b115b09537f/Libraries/Facepunch.Steamworks/SteamServer.cs#L85-L86

**Comment by Regalis11** [comment]
Thank you for taking the time to share this info!

I think we (partially) figured out the issue; it seems SteamCMD tries to launch DedicatedServer.exe for some reason, despite the launch configuration being ./DedicatedServer on Steam's side. We added a script that redirects DedicatedServer.exe to the actual executable now, so creating the symlink should no longer be needed.

The game would also fail to set the environment variables mentioned above if the steam_appid.txt file wasn't present. This should be fixed now as well.

So, please update your servers and let us know if you still run into any issues. Sorry for the inconvenience!

**Comment by Jlobblet** [comment]
Hi,
I've just updated and done a clean install. Still getting the same error as before. Resolved by creating a symlink `~/.steam/SteamApps/common/Barotrauma\ Dedicated\ Server/linux64/steamclient.so` to `~/.steam/sdk64/steamclient.so` (step 4 on my guide).
Hope this helps.

**Comment by thehollowedone** [comment]
Those who still have issues with the guide, check your install location to confirm you aren't setting up broken symlinks.

**Comment by hk135** [comment]
Hi All
Just to add I had to link steamclient.so in the following locations (in the following order)
Barotrauma\ Dedicated\ Server/lib64/steamclient.so
Barotrauma\ Dedicated\ Server/linux64/steamclient.so
Barotrauma\ Dedicated\ Server/steamclient.so

Only once the last in this list was linked did the server start without this error.

**Comment by Rokvach** [comment]
There hasn't been any further discussion about this issue, so I'm assuming the issue has been handled correctly and will close this ticket.

**Comment by Jlobblet** [comment]
Hi,
Installation using `steamcmd` still requires manual intervention.
When running through `steamcmd` and fresh install, I still found it necessary to create a symlink for `steamclient.so`. Both of the following worked:

- Creating a symlink from `"Barotrauma Dedicated Server/linux64/steamclient.so"` to `~/.steam/sdk64/steamclient.so`
- Removing the file `"Barotrauma Dedicated Server/steamclient.so"`, then creating a symlink from `"Barotrauma Dedicated Server/linux64/steamclient.so"` to `"Barotrauma Dedicated Server/steamclient.so"`

This makes me think the problem is with the file `"Barotrauma Dedicated Server/steamclient.so"`. 
Hope this helps.

**Comment by PJB3005** [comment]
I made the same issue. It seems that the game is shipping an outdated version of `steamclient.so`. I couldn't get it to work even with @Jlobblet's instructions but after copying the `steamclient.so` from my own machine (in `~/.steam/steam/linux64/` to the server (installed via steamcmd) it works.

**Comment by Fatmice** [comment]
This problem still exist. ```1026340``` ships with two steamclient.so. One resides at the install root and the other under linux64/. Why are neither of them utilized by ```DedicatedServer``` ? "Normal" convention is to look for "local" libraries within the same directory from whence ```DedicatedServer``` was called.  Indeed, the executable does emit these 
```dlopen failed trying to load:                                                                                                                                                        steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/ubuntu/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
```
It is not clear why the "local" steamclient.so can not be loaded. There is nothing wrong with file permission as the same file when symlinked to ~/.steam/sdk64/steamclient.so will satisfy the executable.  What are you guys doing? Did you compile hard paths into your ```DedicatedServer``` ?

**Comment by friendlykepler** [comment]
Want to add my own findings to this thread.

Currently the dedicated server ships with a steamclient.so file in the root directory. Attempting to run the server results in:
```
steam@0f96b789f724:~/barotrauma-dedicated$ ./DedicatedServer
Barotrauma Dedicated Server 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/steam/.steam/sdk64/steamclient.so
Selected sub: Azimuth
Selected shuttle: Hemulen
[09/12/2020 21:05:13]
  Starting the server...
[09/12/2020 21:05:13]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__47 threw an exception: InitGameServer returned false (0,36318,27015,27016,2,"1.0.0.0")
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in /home/joonas/Barotrauma/Libraries/Facepunch.Steamworks/SteamServer.cs:line 94
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 26
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext() in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 195
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 212    
```

If you create a symlink to the 64bit library that ships with steamcmd then you can resolve this issue:
```
mkdir -p "/home/steam/.steam/sdk64" \
    && ln -s "/home/steam/steamcmd/linux64/steamclient.so" "/home/steam/.steam/sdk64/steamclient.so"
``

Results:
```
steam@0f96b789f724:~/barotrauma-dedicated$ ./DedicatedServer
Barotrauma Dedicated Server 0.10.4.0 (ReleaseLinux, branch release, revision 965c31410a)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
Selected sub: Azimuth
Selected shuttle: Hemulen
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Loaded '/home/steam/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so')
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
CApplicationManagerPopulateThread took 1 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
Warning: failed to init SDL thread priority manager: SDL not found
RecordSteamInterfaceCreation (PID 65): SteamGameServer013 /
RecordSteamInterfaceCreation (PID 65): SteamUtils009 /
Setting breakpad minidump AppID = 602960
RecordSteamInterfaceCreation (PID 65): SteamGameServer013 /
RecordSteamInterfaceCreation (PID 65): SteamUtils009 /
RecordSteamInterfaceCreation (PID 65): SteamNetworking006 /
RecordSteamInterfaceCreation (PID 65): SteamGameServerStats001 /
RecordSteamInterfaceCreation (PID 65): STEAMINVENTORY_INTERFACE_V003 /
RecordSteamInterfaceCreation (PID 65): STEAMUGC_INTERFACE_VERSION014 /
RecordSteamInterfaceCreation (PID 65): STEAMAPPS_INTERFACE_VERSION008 /
[S_API FAIL] Tried to access Steam interface SteamNetworkingUtils003 before SteamAPI_Init succeeded.
RecordSteamInterfaceCreation (PID 65): SteamNetworkingUtils003 /
RecordSteamInterfaceCreation (PID 65): SteamNetworkingSockets008 /
Warning: failed to set thread priority: set failed for priority 8
Warning: support for elevated priorities is most likely unavailable, suppressing future warnings
[09/12/2020 21:12:02]
  Starting the server...
[09/12/2020 21:12:02]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                
[09/12/2020 21:12:08]
  Server started
```

I've created a dockerfile that builds everything: https://github.com/friendlykepler/baroserver

**Comment by CP44** [comment]
I'm checking to see if this is the current/active/best issue to note Linux server issues.  I have not had a successful start of the Linux dedicated server since I first started trying it.
Windows dedicated server retrieved via steamcmd seems to work fine.  Linux goes as follows (and launching with app_run does not look any better)...

Ubuntu 18.04.5 LTS, no GUI

```
steam@baro0:~$ /home/steam/Steam/steamapps/common/Barotrauma\ Dedicated\ Server/DedicatedServer
Barotrauma Dedicated Server 0.10.5.1 (ReleaseLinux, branch release, revision 9e259b2148)
Loading game settings
Loading MD5 hash cache
Initializing SteamManager
Initializing GameAnalytics
Initializing GameScreen
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /home/steam/.steam/sdk64                                                     /steamclient.so
Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
Selected sub: Humpback
Selected shuttle: Venture
[10/9/2020 12:23:55 PM]
  Starting the server...
[10/9/2020 12:23:55 PM]
  Using Lidgren networking. Manual port forwarding may be required. If players cannot connect to the server, you may want to use the in-game hosting menu (which uses SteamP2P networking and does not require port forwarding).                                                                     
Coroutine Barotrauma.Networking.GameServer+<StartServer>d__47 threw an exception: InitGameServer returned false (0,59165,27030,0,NoAuthentication,"1.0.0.0")
   at Steamworks.SteamServer.Init(AppId appid, SteamServerInit init, Boolean asyncCallbacks) in /home/joonas/Barotrauma/Libraries/Facepunch.Steamworks/SteamServer.cs:line 93
   at Barotrauma.Steam.SteamManager.CreateServer(GameServer server, Boolean isPublic) in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/SteamManager.cs:line 24
   at Barotrauma.Networking.GameServer.StartServer(Boolean isPublic)+MoveNext()
in /home/joonas/Barotrauma/Barotrauma/BarotraumaServer/ServerSource/Networking/GameServer.cs:line 195
   at Barotrauma.CoroutineManager.IsDone(CoroutineHandle handle) in /home/joonas/Barotrauma/Barotrauma/BarotraumaShared/SharedSource/CoroutineManager.cs:line 212
```

**Comment by Fatmice** [comment]
@CP44 @3o66 Are you utilitizing the work around?

**Comment by CP44** [comment]
Thanks, @Fatmice.  I needed the hint to try again.  (Success below)
I _had_ looked through the older fixes from Jlobblet with all of the "NB: this has been fixed now." notes.  Seeing LGSM also declare the server dead while linking to this issue made me think this was known-broken.  I thought I had checked the libraries (and failed) and mistakenly thought that the steamclient.so text wasn't critical (other paths being checked & server startup kept going before displaying the final/fatal errors).  Tonight, I saw your message and was asking **_which_** 'the work around' was meant... and when I tested @friendlykepler's link path for steamclient.so , it was suddenly useful in getting to  "Server started" ... I had been through a variety of path names, and linking files depends on knowing the locations of files -- both what's missing and where the correct file exists.  Before tonight, I had tried this and failed.  It seems `.steam/sdk64/steamclient.so` from the user's home folder has to be valid or point somewhere, the link target may vary based on where the users installed Steam or steamcmd, and DedicatedServer may try to find steamclient.so in other locations, too.
Right now for me, with version `Barotrauma Dedicated Server 0.10.5.1 (ReleaseLinux, branch release, revision 9e259b2148)`, the link below works, and I'll give the whole process for reproducing an installation and why this path works (for me).
**ls -l ~/.steam/sdk64/steamclient.so**
`lrwxrwxrwx 1 steam steam 40 Oct 10 21:41 /home/steam/.steam/sdk64/steamclient.so -> /home/steam/Steam/linux64/steamclient.so`

Now onto the long sample (where # is a comment.  If you paste all of the lines below into a terminal/SSH/PuTTY window at the same time, expect to have problems with sudo prompting for a password.  Running/pasting them separately should be fine.  If you're on Arch/Manjaro, etc... expect to do more things differently.)

```
# I start as user "steam" and am using a distribution that uses apt for packages (Ubuntu Server).
# I start by setting up "Steam" within the user's home folder as the Valve guide suggests.
mkdir ~/Steam
cd ~/Steam
wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
tar -xvf steamcmd_linux.tar.gz
# ^ Or use curl as the Valve guide suggests which replaces both of those commands, but I like having the installer file around in case of starting over.

# Install screen to easily allow programs to run detached later
# Also install a preferred text editor if needed (using "vim" below for the example; apt will say if it's already installed, which does not change the steps)
# ...or do these from root if current user cannot use sudo
# ...or ignore this part: don't use screen and don't change text editors
# ...as long as you can edit a text file
sudo apt update
sudo apt install -y screen vim

# Get the dedicated server; using screen in case SSH drops during steam/steamcmd/dedicated server download
screen ~/Steam/steamcmd.sh +login anonymous +app_update 1026340 +quit

# The important symbolic link after making the directory for it (.steam/sdk64 in the user's folder), which I am doing without making it conditional so that this can be run more than once without changing the behavior of the second command
# Also, do not use double quotes while using ~ to represent the user's home folder.
mkdir -p ~/.steam/sdk64 ; ln -s ~/Steam/linux64/steamclient.so ~/.steam/sdk64/steamclient.so

# Edit the serversettings.xml file. Save changes when finished.
# If not vim, try vim.tiny , vim.basic , or nano , or vi , or find out what text editor you do have and how to use it.
vim ~/Steam/steamapps/common/Barotrauma\ Dedicated\ Server/serversettings.xml

# Run the Dedicated Server so that the terminal is handled by screen and can be detached...
# Ctrl+A then D to detach, Ctrl+C to abort the server, "quit" to shut it down nicely, 
# screen -r to reconnect later (or look up the manual for "screen")
screen ~/Steam/steamapps/common/Barotrauma\ Dedicated\ Server/DedicatedServer
```

#Results:
DedicatedServer runs
Server was successfully joined from the master list (with manual port forwarding)
Steamcmd's actual full path:
`/home/steam/Steam/`steamcmd.sh
Game server's actual full path:
`/home/steam/Steam/steamapps/common/Barotrauma Dedicated Server/`DedicatedServer

**Comment by JoneKone** [comment]
https://linuxgsm.com/ Just use something already working.

**Comment by dopeghoti** [comment]
I just attempted for the first time today to install the _Barotrauma_ Dedicated Server in Linux via SteamCMD and got the error mentioned in the issue-opening comment.  Happily, the steps @Jlobblet outlined in their comments at this link (https://github.com/Regalis11/Barotrauma/issues/2310#issuecomment-600180323) were able to get me up and running.  I'm commenting primarily to provide another data point confirming this issue and the current workaround.

**Comment by moeilijk** [comment]
> 
> 
> I just attempted for the first time today to install the _Barotrauma_ Dedicated Server in Linux via SteamCMD and got the error mentioned in the issue-opening comment. Happily, the steps @Jlobblet outlined in their comments at this link ([#2310 (comment)](https://github.com/Regalis11/Barotrauma/issues/2310#issuecomment-600180323)) were able to get me up and running. I'm commenting primarily to provide another data point confirming this issue and the current workaround.

Also confirming. Today fresh install of a dedicated server on ubuntu 20.04
Hardlinking or copying the steamclient.so from the steamcmd installation to the BaroTrauma folders and overwriting the (outdated?) existing ones fixes the issue.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c08209cd1472b64c5e63baaddcd59276943787b9. The issue is that we erroneously distribute a very outdated `steamclient.so`, so it fails to connect to Steamworks successfully. The fix is as follows:
- Remove `steamclient.so` from `~/.local/share/Steam/steamapps/common/Barotrauma Dedicated Server/`
- Add the following line to the top of `DedicatedServer.exe` (yes this is the name of the startup script, it's this way because Steamworks doesn't appear to be handling platform-specific filenames correctly):
  - `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PWD/linux64"`

**Comment by Jlobblet** [comment]
Tested with a clean install. The `linux64` directory appears to be missing, and I get the usual bug when starting the server.

**Comment by Rokvach** [comment]
Closing
