### ISSUE TITLE
[Bug] [Modding] Affliction Status Effect Sounds do not work in multiplayer

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2388]
In singleplayer, embedding a sound into a statuseffect in an <Effect> in an affliction will have it play while the effect is within that affliction strength range. This does not work in multiplayer for some reason. Easy to see with my mod.

**Comment by Regalis11** [comment]
Does not seem to be a multiplayer-specific issue: the sound fails to play after quitting one round, because the StatusEffect sounds are loaded as "round sounds" which get disposed at the end of a round. In this case they never got reloaded, because the affliction prefabs aren't reloaded when starting a new round.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e8831bc74df0ff68194999b8667585673635ed3a

**Comment by Rokvach** [comment]
Tested by using the new psychosis additions, working correctly. Closing.

**Comment by hubismal** [comment]
This is still an issue. Modded affliction sounds do not work unless you enable ingamemodswap and disable and re-enable the mod in the middle of the round. Requesting reopen.
```xml
<AfflictionHusk name="Genetic Meltdown (Head)" identifier="thal_meltdownhead" description="The patient's DNA is compromised. With the cells unable to reproduce, the patient is slowly 'melting' into dead cells. Locate a DNA graft to resupply the head with target DNA. The longer meltdown persists, the more genetic disorders are introduced to the patient's genes." type="huskinfection" targets="human, humanapostle" huskedspeciesname="gummy" causeofdeathdescription="Melted into DNA-less goop." CauseSpeechImpedement="false" sendmessages="false" selfcauseofdeathdescription="You have melted into goop." limbspecific="false" indicatorlimb="Head" activationthreshold="0" showiconthreshold="10" maxstrength="100" iconcolors="60,140,195,255;60,107,195,255;60,0,195,255">
    <Effect minstrength="0" maxstrength="80" strengthchange="1" minvitalitydecrease="0" maxvitalitydecrease="30" >
			<StatusEffect target="Character" targetlimbs="Head" duration="0.5" delay="0.5" stackable="false" >
        <ParticleEmitter particle="gib" copyentityangle="true" anglemin="0" anglemax="360" particlespersecond="5" velocitymin="50" velocitymax="200" scalemin="1" scalemax="2" />
			</StatusEffect>
			<StatusEffect target="Character" targetlimbs="Head" stackable="false" >
        <Sound file="Mods/Thalassophobia/Map/Thalamus/eye.ogg" range="400" loop="true" />
			</StatusEffect>
		</Effect>
    <Effect minstrength="80" maxstrength="100" strengthchange="0.3" minvitalitydecrease="30" maxvitalitydecrease="50" >
			<StatusEffect target="Character" targetlimbs="Head" duration="0.5" delay="0.5" stackable="false" >
        <ParticleEmitter particle="gib" copyentityangle="true" anglemin="0" anglemax="360" particlespersecond="5" velocitymin="50" velocitymax="200" scalemin="1" scalemax="2" />
			</StatusEffect>
			<StatusEffect target="Character" targetlimbs="Head" stackable="false" >
        <Sound file="Mods/Thalassophobia/Map/Thalamus/eye.ogg" range="400" loop="true" />
			</StatusEffect>
    </Effect>
    <icon name="genmelt" texture="Mods/Thalassophobia/UI/MainIconsAtlas.png" sourcerect="386,769,128,128" color="60,107,195,255" origin="0,0" />
  </AfflictionHusk>
```
here's the exact xml that gives me problems

**Comment by Rokvach** [comment]
Moving back to todo

**Comment by Regalis11** [comment]
Got some more data about this through GameAnalytics and was able to fix it in https://github.com/Regalis11/Barotrauma-development/commit/a0b5ca6bea9d911fe29338c3c91a1740c73125f7

**Comment by Rokvach** [comment]
This hasn't caused any issues to the vanilla gameplay, I think I'm just going to close it. We can always re-open this ticket if it still does happen once the patch is out. Closing.

**Comment by Rokvach** [comment]
The error mentioned on the commit hasn't shown up in GA since, seems to be fixed. Closing.
