### ISSUE TITLE
Server Freezing, is there a fix/workaround?

### ISSUE THREAD

**Issue by MrTeco** [Regalis11/Barotrauma#3086]
Sometimes my dedicatedServer.exe freezes, it stops sending messages and I can't type commands, and all clients connected are frozen too until they disconnect or I close the server.
How do I fix this?

**Comment by MrTeco** [comment]
Probably need to include more info, but idk what

**Comment by Regalis11** [comment]
@juanjp600 Was this addressed in https://github.com/Regalis11/Barotrauma-development/commit/6ce83f0? Should it be moved to in progress or QA?

**Comment by juanjp600** [comment]
This appears to be a different issue altogether; 6ce83f0 is meant to address issues with the server list specifically, this appears to be a problem with the dedicated server.

**Comment by MrTeco** [comment]
it certainly is annoying as hell, knowing that the server might just stop working any second

**Comment by MrTeco** [comment]
Alright, it seems like this started happening in 0.9.10.0.
Did anything on the master branch change since 0.9.10.0?

**Comment by MrTeco** [comment]
So I updated the server and it still happens, I have no idea why my server freezes. Didn't happen last version, last version it only desynced sometimes and everyone reconnected instantly.

**Comment by MrTeco** [comment]
I would like to get some suggestions.

**Comment by Regalis11** [comment]
No known steps to repro, closing
