### ISSUE TITLE
Purchased items aren't spawned after a round ends in Game Over

### ISSUE THREAD

**Issue by ekqvist** [Regalis11/Barotrauma#3247]
Money is still spent, but the purchased items aren't respawned.

Likely related to #3096.

**Comment by ekqvist** [comment]
Fixed purchased items not being loaded with a save at all in Regalis11/Barotrauma-development@dd43557.

However, there still remains an issue regarding the save not being reloaded after a) returning to lobby and continuing the game; or b) a round resulting in a game over, returning to lobby, and continuing the game. Because `CargoManager.PurchasedItems` is cleared when `CargoManager.CreatePurchasedItems()` is called at the start of the round, it never gets reloaded so it's empty at the start of the next round when hitting Continue.

**Comment by ekqvist** [comment]
Server not reloading the campaign save when continuing a campaign after a game over was fixed in Regalis11/Barotrauma-development@8d46351

**Comment by Regalis11** [comment]
Whoops, didn't notice this was in the public repo and that referencing it in the commit doesn't work

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by UsernameIsToLon** [comment]
This bug persists or is back with the current version of the game.

**Comment by rcoltonclark** [comment]
Hello! this bug is confirmed back or still an issue.

We bought items and then the game needed to be reloaded, when hitting continue we lost everything.

Please re open if closed

**Comment by ekqvist** [comment]
It seems that the issue might be happening again in some form as reported in #7853. If this is the case, it should be fixed in Regalis11/Barotrauma-development@48f7d39.
