### ISSUE TITLE
Outposts always annoyingly generate airlock

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3396]
[Modding, Issue]
The outpost seems to always generates an Airlock module regardless of its inclusion in the outpost configuration. This is especially annoying if you want the airlock for a certain type of location to always be customized, since this forces a vanilla airlock to always have a chance of appearing in every single location type in existence (if you make a module of type "customairlock" or something and tell the game to include it in outposts, you are going to get two airlocks).
It would be nice if we could turn this off in certain outpost configs. Or if the game just trusted itself enough to not generate a backup airlock if it doesn't detect a module of type Airlock.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f16263b3802140931ae958379f725da60869177e: the generator now uses the module that's defined 1st in the outpost config as the initial module.

**Comment by Rokvach** [comment]
Not fully sure how to test this but I tried couple things, in OutpostGenerationParameters.xml I first removed all the entries containing Airlock, that causes a error to come up. Then I tried to replace all the entries with a different module name other than Airlock but still received the same error when trying to start the game.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b15b6703-6a46-40f8-915c-423e3db94dbe)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
