### ISSUE TITLE
Various Servers are Considered "Playstyle-less", Affecting Server Filters

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#3612]
Some servers are considered "without a playstyle", and will show up for some reason when absolutely all playstyles are filtered out. They take on the appearance of Serious servers. A few Discord members are complaining about them since this means that these "serious" servers will start showing up in every other single category filter (ex "serious" servers will show up in just roleplay, just casual, just rampage, etc).
**Reproduce:** Open server browser, turn off all the inclusive filters for playstyles.
Should see something like below:
![image](https://user-images.githubusercontent.com/47284081/90946759-a7354400-e3f5-11ea-8c20-b3d01b763419.png)

**Comment by EtiamNullam** [comment]
I can confirm. At the time I checked all of them without category were empty, so they all are dedicated servers - server hosted over steam p2p can't be empty.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ba824f75e6f3e040ebe3de05b5a12824e74a897e

**Comment by Rokvach** [comment]
I think we should also not show the servers if a playstyle has been selected, is it a bug that the servers doesn't have any? 

One way to do this would be to add a "None" playstyle and being able to toggle those servers off from the list

- [ ] The playstyle is still being shown as serious even if the server doesn't have the banner
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/35552db7-5405-4ce9-a92a-2172f8bdfb4c)

@Regalis11 

Game modes seems to have similar issue where certain servers are always shown even tho you don't have any game modes toggled on, as well as showing servers doing campaign when the list has been filtered to only show mission game mode.

**Comment by Regalis11** [comment]
Those should be fixed now: https://github.com/Regalis11/Barotrauma-development/commit/40057c29f43ad01b06ed054acb64fa78603f26c4

Normally the servers should always have a play style set, but there's a bug in the current version that causes dedicated servers to not report the playstyle to the master server.

Since there should be no "playstyle-less" servers after the fix goes out, instead of a "None" filtering option I decided to only show them when all playstyles have been selected. The "Playstyle: Serious" text should also now be hidden.

**Comment by Rokvach** [comment]
Tested, didn't find any issues. Closing.

**Comment by EtiamNullam** [comment]
@Regalis11 despite of what you said a dedicated server I hosted in 0.10.505.0 (unstable) appears only when all the playstyles in filtering are selected. Or is it not supposed to be fixed yet and all dedicated servers are still "playstyle-less"?

**Comment by EtiamNullam** [comment]
Still does not work in 0.10.5 (unstable), my dedicated server is always considered "playstyle-less" - after last fix unchecking any of the playstyle in server browser filtering will make my server disappear from the list.

**Comment by ekqvist** [comment]
Reopened and moved back to to-do

**Comment by Regalis11** [comment]
Third time's a charm? https://github.com/Regalis11/Barotrauma-development/commit/d00035b12d3a2a8fa75cf26a11844aa674c35e35

**Comment by Rokvach** [comment]
No issues, closing.
