### ISSUE TITLE
[Bug] Possible issues regarding some Outpost Events

### ISSUE THREAD

**Issue by KennyNathan** [Regalis11/Barotrauma#4046]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
These are the Outpost Events that I found to have flaws or possibly not work properly:
- [x] Engineers are special: Successfully fixing the engine will give discount for Upgrade, according to the conversation. This seems yet to be implemented. 
- [x] Propaganda: I can't seem to ever encounter or trigger (using console) this Event. Upon reading the xml, this Event is activated if the player is near the "hrflyers", which is probably the Notice Board located in the HR Office where Crew Management is accessed or even the Propaganda Banner, which makes more sense, tho I rarely see it. I have tested this countless times, not just running to the potential flyers, but also basically going through every nook and cranny in the Outpost to activate it, all to no avail. This Event is either bugged or ridiculously rare, which is unlikely since I even tried to get it through Console (and it's the only Event I couldn't activate by any means).
- [ ] Sleight of Hand: Still has money issue. Can join the bet with 0 mk. Also, if the player wins the bet, the reward item doesn't spawn in the inventory. If the player successfully tries to steal the item, however, the Alien Trinket is rewarded in the inventory. 
- [x] Clown Brutality: According to the xml, this Event is supposed to have 2 Clowns fight a random Commoner. Tho the Event spawns these entities as intended (2 Clowns, 1 Commoner), the Clowns don't start attacking at all.
- [x] Black Market: This Event is broken in terms of branching outcomes. Have tested many items and I always end up with the genuine Alien Pistol route. Also, when receiving the weapon, the conversation text has a typo: "He hands you the pistol. It's a genuine article." Article = Artifact.
- [x] Impromptu Engineering: When the player successfully repairs the terminal, they have the option to either "Request free coilgun ammunition." or "Install an old-school first-person shooter on the system." If they choose Coilgun Ammo, the conversation text is as follows: " After clicking around a bit, you successfully order two boxes of coilgun ammunition for your vessel, free of charge." The text says two Coilgun Boxes, but only 1 box spawns in the main sub. This is either a typo in the text (one instead of two) or the xml misses a <SpawnAction> for the second Coilgun Box.
- [ ] Giving Directions: There's a slim chance the captain's Revolver may only have 1 Round in it even tho in the xml, there's no such value to determine how many Rounds may spawn in the gun, but only the code to spawn 3 Rounds in the gun, which should be consistent (tested from succeeding to steal the gun, failing to steal the gun and sometimes getting shot once but most other times getting shot 3 times as intended for a gun loaded with 3 Rounds, or straight up stun the captain to check his gun).
- [x] Taste Test: If the player passes the Medical skill check "Take a closer look at the bottles." option, they'll be able to identify the bottles and proceed through the dialogue by "Bottoms up!" the solution. But when they choose the last option "Not bad.", the Event box doesn't disappear even after the player is prompted to check the trash can again, it will still persist. Only when the player finishes the whole Event by obtaining all the Chemicals in the trash can will the Event box disappear. This means during the period of waiting for the solution to take effect and approaching the trash can to obtain said solution, the Event box is stuck onscreen, obscuring the view basically. This doesn't occur if the player fails the initial skill check and proceeds to the blindly guessing bottles route, the Event box disappears after the player drinks the correct bottle and waits for effect, comes back to prompt the player to check the trash can, disappears again, then comes back to show the final line of the Event as intended.
- [x] Mediator: Pretty minor. If the player passes the Helm skill check and settle down the 2 arguing workers, instead of getting +5 for Helm, the game gives +5 Electrical. This can be also be found within the xml, I suspect it's a typo cuz it just doesn't make sense, there's no correlation between the 2 skills as far as I know.
<SkillCheckAction targettag="triggerer_player" requiredskill="Helm" requiredlevel="70">
                <Success>
                  <GiveSkillEXPAction skill="electrical" amount="5" targettag="triggerer_player" />

**Steps To Reproduce**
I'm a bit late to report this, so most of these may have already been worked on in Unstable, but guess I'll just follow the format:
- Engineers are special: The easiest way is to just give +RP for the current Outpost for the Engine fixed route so Upgrade gets a discount, but this may also lower the price of other departments, which might not make sense. The only thing I can think of is to add a separate value (maybe call it Discount) to this Event, where the Discount value is specifically added to the Upgrade section in the current Outpost only, and maybe the Event's commoness becomes 1 or 0 or whatever value that makes it no longer triggerable in that Outpost. And the Discount can either be permanent or last for some "duration" and when the duration ends, the Discount is removed and the Event can be triggered again in that Outpost.
- The rest: like... idk what to say, fix them I suppose? I think I have explained their issues as thoroughly as I can.

**Version**
v0.10.5.1 Windows

**Additional information**
This doesn't really bother me much, but I might as well bring it up. In Giving Directions, there was a couple times where after succeeding in stealing the captain's revolver, it was only loaded with one Round, even if in the xml, 3 Rounds were supposed to spawn in the gun. This issue is furthered reinforced when I failed this and the captain only shot me once and other times he shot me 3 times, the latter is the more occasional occurrence. No idea why this sometimes happens. 
Hopefully the devs can work these out. Thank you!

**Comment by Regalis11** [comment]
Thank you for a very informative report!

Fixed "black market" in https://github.com/Regalis11/Barotrauma-development/commit/cc477562497236c37f7015aa2529d21f618d7c11 and "impromptu engineering" in https://github.com/Regalis11/Barotrauma-development/commit/65ad6964e1b3256bb8121abbba5f032961cd9da6. Left "genuine article" unchanged - it's not a typo, it means "article" as in item or an object.

Also, as a note in case you'll be doing bug reports in the future, the "steps to reproduce" part basically means "how we can get the bug to happen" (let's say, "the game crashes when I do things X, Y and Z in this order"). In this case it's pretty obvious from the description though.

**Comment by KennyNathan** [comment]
Ah! I see lol. Sorry about that. I'll keep that in mind in the future. Great job so far with them buggers!
Hmm... Article, I see. It's surprisingly similar to Artifact, but I find article a bit odd for the ears because going through the Event all you see is Artifact, then at the end, it becomes a generic "article", which threw me off caught. But if it's not a typo, I guess it's all good!

**Comment by KennyNathan** [comment]
I added Giving Directions to the main list as further testing proves this may be an issue that needs fixing, just in case the devs accidentally glossed it over in the Additional information section :)

**Comment by danielasteljoki** [comment]
I wasn't able to reproduce the revolver issue. It might have been fixed already. Leaving this for QA to determine if the issue persists.

**Comment by KennyNathan** [comment]
Yeah, it actually sometimes takes a lot of retries to get the variation of Revolver with 1 Round currently on Stable v0.10.5.1. Hopefully it's already resolved!

**Comment by KennyNathan** [comment]
Added Taste Test Event to the list as I stumbled upon a bug earlier where Event Box doesn't collapse in the success Medical skill check route. The list just keeps piling on lol Sorry!

**Comment by KennyNathan** [comment]
The more the merrier! I found another one, so Mediator is added to the list. Conflicting skill check and skill reward in the xml, which happens in game too.

**Comment by danielasteljoki** [comment]
Fixed the last two issues in the list (c5be4df).

**Comment by KennyNathan** [comment]
Nice. Took your sweet time tho :D Only Sleight of Hand and possibly Giving Directions if it ain't fixed yet. So far I haven't found any more bugs in Outpost Events, so this is good news.

**Comment by Xeavas** [comment]
**No issues noticed in :**
- Clown Brutality (correctly attacking)
- Black Market (gives the eggs variant and good and bad outcomes for both variants)
- Taste Test (no event display issue)
- Mediator (gives correct skill when pass skill check)

**Issues found in :**
- Engineers are special
You will receive the skill check before you select to help or refuse, thus giving you 5 levels of mechanical xp without even required to choose to help. Assuming "discount" is the relation with the outpost boost, rather than a separate discount for the upgrade menu.

**Cannot manage to get listed events to spawn/trigger with console :**
- Propaganda
- Impromptu Engineering

**Comment by KennyNathan** [comment]
I knew it wasn't just me. I still can't manage to trigger Propaganda, it's so bizarre. Haven't tried Engineers one, but that sounds like a whole new issue there.
idk if I should close this and open a new one with current Outpost Event problems in v0.10.6.2 since this Issue page was made for v0.10.5.1.

**Comment by Xeavas** [comment]
No need to close, it's still an ongoing issue, I cannot manage to get `Propaganda` to trigger due to me not knowing what "potential flyer" is.

**Comment by KennyNathan** [comment]
I see. I'm just worried this Issue will get overshadowed by new ones. And I always thought the "potential flyer" could be the HR flyers on the Notice Board or the actual Propaganda Banner (can be found in Sub Editor) located in the HR office/area/hull.
Also, I still haven't got any solid confirmation if Giving Directions has already been checked out and if Sleight of Hand has been dealt with yet.

**Comment by Xeavas** [comment]
Done some further tests, updated my test list, it seems like it does spawn naturally but something with the tags and the event not recognising the required item cause it to not trigger as seen in trying to spawn them in via console commands.

From your original comment there's a checklist, don't think they got to tackling that just yet.

**Comment by KennyNathan** [comment]
That sounds complicated. I suppose something can be done with the tag then.

And yeah, hope so!

**Comment by danielasteljoki** [comment]
Fixed Engineers_are_special skill exp action and propaganda event. Flyers are structures instead of items, which caused the 'potentialflyers' tagging to fail.

**Comment by Xeavas** [comment]
[0.1100.0.2] - `Engineers_are_special` is now working as intended and `propaganda` is now properly triggering 👍

**Comment by Rokvach** [comment]
Closing

**Comment by Xeavas** [comment]
Since this is closed I'll note that `sleightofhand` is still an issue from the original report, no comment on `givingdirections`.
