### ISSUE TITLE
Bots do not account for line of sight to fire when trying to extinguish fires

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#4349]
**Description**
They do not account for obstacles/objects in the way blocking the ability for fire extinguishers to reach the flames.

**Steps To Reproduce**
- Spawn into outpost
- Set fire in the area of outpost terminal using `fire` command
- Observe for result

![extinguisherlos](https://user-images.githubusercontent.com/72674994/99681374-079d5580-2ab9-11eb-8b4f-97b57a229fbe.jpg)

**Version**
[0.1100.0.7]

**Comment by itchyOwl** [comment]
Possibly fixed by Regalis11/Barotrauma-development@4e026da.

**Comment by Rokvach** [comment]
Tested on dev (The commit for some reason doesn't show the branch)

Started a fire right over the switch terminal and teleported all bots out of the bottom half of the docking module and just waited until a bot noticed it, they did notice the fire really fast but weren't able to find any fire extinguishers even though there were multiple of them right next to the fire

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/e18cba1b-a33a-4a5f-b9a3-156caf9b97bf)

Now the room is fully engulfed in fire and the bots aren't trying to find fire extinguishers anymore, those who tried to find them previously are now on find safety order instead and runs around the outpost. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/638fd30f-57ac-4035-ae69-ef6291c58c31)

**Comment by itchyOwl** [comment]
There was an issue with the line of sight, fixed it in Regalis11/Barotrauma-development@9d3e507.

However, I can't reproduce the issue @Rokvach mentioned. Are you sure the bots were even trying to exinguish the fire and not just running away from it? Did you try to order them to put off the fires?

**Comment by Xeavas** [comment]
@itchyOwl as of [0.1200.0.2] its more rare, but it still happens at times, for the los.
![firet2](https://user-images.githubusercontent.com/72674994/104808363-a546a400-5820-11eb-9c0b-42fa45ec6530.jpg)

As for what rokvach found, I suspect they have difficulty fighting fires directly below or above them, in a funnel like fashion, possibly with ladders, as they have no issues fighting fires in a way seen in #4138. They either run into the fire to extinguish it, or sit below or above going in and out the state of "find safety" while doing nothing to help fight the fire (even when I ordered one of my bots to do so) 

![firet1](https://user-images.githubusercontent.com/72674994/104808398-f2c31100-5820-11eb-8ba3-0af73b38a01d.jpg)
As you can see, the room directly above of them is fully engulfed with fire, with 3 bots holding fire extinguishers but standing still.

**Comment by Rokvach** [comment]
Moving back to misc todo

**Comment by itchyOwl** [comment]
Both issues should be fixed in Regalis11/Barotrauma-development@784daac.

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce. Working correctly. Closing.
