### ISSUE TITLE
ALL shuttles appear on the sonar with a name tag and distance in PvE, and the opposite in PvP

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#5297]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
ALL shuttles spawned in PvE appear on the sonar with a name tag and distance
This includes respawn shuttles, but also shuttles attached to Wrecks/Beacons.
![image](https://user-images.githubusercontent.com/73229309/112229563-7dfebf80-8c33-11eb-98ed-2983df8e0157.png)
_Naval Mine is a shuttle linked to a wreck_

Wrecks/Beacons aren't located on the sonar by default (unless mission objectives), but their shuttles are
In PvP however, all shuttle/sub name tags are hidden, even from your own team so you can't know where your own shuttles are.

**Steps To Reproduce**
Add the "Naval Mine Dropper" wreck in the wreck pool (using [wrecks mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2184257427) or otherwise) 
[Naval Mine Dropper.zip](https://github.com/Regalis11/Barotrauma/files/6193217/Naval.Mine.Dropper.zip)
Launch a mission
The mine appears on sonar (but the dropper doesn't)

**Version**
v.0.12.0.3 

Not sure if all shuttles should be hidden/show by default, as both making them visible/invisible on sonar have building implications, so ideally having a "show/hide" option would help

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f73dcabcfcba45a161db853fe7b356afa7953f29 and https://github.com/Regalis11/Barotrauma-development/commit/7a87c980f202cb259fd67d9d185d5f94bd038a53

**Comment by ubertpendragon** [comment]
Tested on Unstable today

- [ ] In PvP, allied submarines/shuttles appear to allies, enemy submarines/shuttles are hidden  

- [ ] Third-party shuttles do not appear on the sonar from afar, no visible name tag

- [ ] Docking ports however still appear on the sonar (green line)

**Comment by Regalis11** [comment]
Should be fixed now: https://github.com/Regalis11/Barotrauma-development/commit/6a352f7c1c06a1d22d21228001acf03a7ba9447b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Regalis11** [comment]
The previous fix prevented outpost docking ports from being drawn, fixed in https://github.com/Regalis11/Barotrauma-development/commit/6a352f7c1c06a1d22d21228001acf03a7ba9447b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
