### ISSUE TITLE
[1300.0.x] Mission Screens: Selected Mission vs mouse-hover color confusion

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#5539]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
On the mission selection screens the color of a selected mission is the same as the color when you hover the mouse over a non-selected mission, leading to confusion.
Me and my buddies know about this and still we sometimes start without having a mission selected because the mouse-hover confused us into believing a mission was selected.

Expected: A more clear indication which mission is selected vs the mission thats just highlighted by the mouse hover.
Suggestion: Simply remove the color change from mouse hover - its not really needed. Or keep the highlight color but draw a frame around a selected mission.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4ae38f31255dd8921a152f527b438cf57e42817e

**Comment by Rokvach** [comment]
I think its a lot more confusing now as the selected mission stays disabled when your mouse is over it which gives the wrong feedback of the mission not being able to be interacted with or not selecting. 

I'd remove the hover functionality from the currently selected mission entirely, so you can still see that its selected when your mouse is over it.

**Comment by Regalis11** [comment]
Will be addressed alongside https://github.com/Regalis11/Barotrauma-development/issues/2489
