### ISSUE TITLE
[Unstable] Creatures that aren't supposed to eat bodies can eat bodies while player controlled

### ISSUE THREAD

**Issue by Emanthealmighty** [Regalis11/Barotrauma#6534]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While playing as a monster, you can press G to eat dead bodies.
The ability to eat dead bodies as a monster is decided by a new parameter that was introduced along with this PR https://github.com/Regalis11/Barotrauma/pull/5563 called "caneat".
If "caneat" is set to true, then the monster is allowed to eat bodies while player controlled. However, this parameter is set to true by default, and it hasn't been set to false for any monster. This means that you can eat dead bodies while playing as any monster.

**Steps To Reproduce**
1) Spawn as a monster that doesn't eat bodies when AI controlled (fractal guardian, hammerhead, husked crawler, etc)
2) Find a corpse, press G while near it to begin eating it

**Version**
V0.1500.0.0 Unstable

**Additional information**
I think that this parameter should be set to false by default and be set to true only for those monsters that are supposed to be able to eat bodies, such as crawlers, tiger threshers, mudraptors, etc.

**Comment by itchyOwl** [comment]
What decides whether a creature should be able to eat corpses or not? Until now it was just a matter of having a head and for AI controlled characters being told to target corpses. So that's why the new parameter defaults to "True". I set it "False" for some creatures, but I think it's fine to allow players eat bodies as long as the creature has some kind of mouth that could be used for it.

Disabled the "caneat" parameter for:

- Hammerheads
- Terminal cell
- Leucocyte
- Molochs
- Spineling
- Watcher

Fixed in Regalis11/Barotrauma-development@11fdd7d.

**Comment by Emanthealmighty** [comment]
>What decides whether a creature should be able to eat corpses or not?

Originally I thought this should be just a matter of whether or not they have an "eat" state in their AI parameters.

>I think it's fine to allow players eat bodies as long as the creature has some kind of mouth that could be used for it.

But letting other creatures that _look_ like they should be able to eat corpses eat them is good too.

Issue is not fixed as of v0.1500.1.0 (Unstable). Was able to eat a corpse while playing as a hammerhead and spineling.
I wasn't able to eat as the other creatures, though an "eat" prompt did show up anyway.

Upon inspecting the creatures' XML files, "caneat" seems to not be mentioned in any of them.

**Comment by itchyOwl** [comment]
I suspect the commit didn't make it to the build. I don't know exactly from which commit the build was made from (we should probably mark that with a tag?)

**Comment by Emanthealmighty** [comment]
Working properly as of v0.1500.2.0 (Unstable).
Creatures without a visible mouth are unable to eat bodies.

**Comment by Rokvach** [comment]
Closing
