### ISSUE TITLE
Glitching through the floor using ladders

### ISSUE THREAD

**Issue by mumu2qua** [Regalis11/Barotrauma#7107]
- I have searched the issue tracker to check if the issue has already been reported.

**Description**
If you hold ctrl and go down the ladder, you will faze through the floor

**Steps To Reproduce**
Get on the ladder, hold ctrl and go down the ladder

**Version**
v0.15.12.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4fd6351f0afa2b09ad8f96a330c9894991a652c1

**Comment by Rokvach** [comment]
I was still able to reproduce the dangling issue when moving from Dugong to Outpost
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/80ebfcb0-4a52-400f-824b-35ced43c0623)

This fix doesn't seem to cover hatches, so the behavior of character trying to go downwards still exists when your character is on top of a hatch. You might not be able to phase through the hatches but I was at least able to momentarily break the characters ragdoll by doing this.
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/21b63762-9684-4bba-856c-ba258f4c3a67)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c8d1998b044cc6ff251179f7344ae5a6a1999cb8 and https://github.com/Regalis11/Barotrauma-development/commit/1be2991a6a58a026a062f7fbd2c873a729b4723b

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
