### ISSUE TITLE
Bots - Diving Suit Lockers (Also probably Oxygen Tank Shelves) are not ignored when they're "Hidden In Game"

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#8366]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just found out that one of my sub had a diving suit locker that was accidently hidden in game. Turns out that was the reason why bots were constantly getting stuck in front of where it would be. 

**Version**
0.16

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@4fac29b.

**Comment by Lithosagym** [comment]
Tested, items marked as "Hidden In Game" are indeed ignored by bots, A bot preparing for an expedition will not get stuck on trying to grab hidden oxygen tanks or diving suits. This issue is fixed.

Of course, this is not applied for more contextual commands, as bots will still get stuck on trying to interact with a hidden navigation terminal, periscope, or nuclear reactor. Bots will also get stuck when trying to repair a hidden object.

**Comment by Rokvach** [comment]
Moved to Team2 as we need to take a look at the contextual orders

**Comment by itchyOwl** [comment]
So, does it not work with contextual orders or what's the issue?

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
