### ISSUE TITLE
[Unstable 0.17.9.0] Something is wrong in file transfers on dedicated server

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8785]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Each time I join my own dedicated server which has some custom subs I get this notification
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/43634af1-86cd-4d58-9f56-add617f06d71)

Whenever a new player joins the server and starts downloading a custom sub or the campaign save the dedicated server console is spammed with this

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2d2492fe-422b-4c65-b998-fd2abcc10be7)

I haven't hosted in Steamp2p for couple builds now so can't say if the same happens there.

**Steps To Reproduce**
No idea what is causing it or how. 

**Version**
Unstable 0.17.9.0

**Comment by Regalis11** [comment]
I was able to reproduce the first popup pretty reliably by doing the following:
1. Start a dedicated server with a handful of custom subs (in my case Immortal X, Zenith Gaurd and Humpback PVP).
2. Set simulated latency to 0.1 and 0.01
3. Try to join the server

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/0e1ab644be46974e86d4feaf18d7531a9508f5f6

**Comment by Regalis11** [comment]
Still haven't managed to repro the dropped packet issue, let's wait and see if we still run into it after that fix

**Comment by Rokvach** [comment]
Dropped message still happens but the transfer message hasn't appeared at all after the fix so thats working. 

Seems like the server has to have a mod installed(even a small one) and the player joining has to have a ping higher than 150 for the dropped message to be spammed. In one case the download of the mod got stuck at 0 b / 0 b for one of the players who got the dropped message spam.

**Comment by Rokvach** [comment]
The bigger issue is now fixed so I think I will close this ticket, can write a new ticket about the dropped message issue if needed. Closing.
