### ISSUE TITLE
Dead pirate sub "glued" on top of the sub

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#9319]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

We broke, flooded and killed a pirate sub that dropped on the roof of our sub.
There was no way to "wiggle" it off somehow. 
Even tried to stripe it off on the edge of a cliff, but it was glued to our hull.

Its a very annoying behaviour even with the perspective that fixing the pirate sub can be somewhat interesting to separate the subs again. Yet, they shouldnt stick together like glued in the first place.

Expected behaviour: less grip, more intertia of a flooded dead sub vs an active sub that tries to move away from under it.

### Reproduction steps

see above

### Bug prevalence

Happens regularly

### Version

Other

### -

tested on different .18.x versions (latest .18.6)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
none
```

**Comment by mygamingaccount** [comment]
Fix the damaged submarine and it will lift off

**Comment by Renmusxd** [comment]
This sometimes works - but on the pirate Humpback there seems to be a non-repairable hull piece (or one that my whole crew could not figure out how to repair) near the nose. I think it's because the exterior nose cone counts as a wall but doesn't interact properly with the welding torch?
We were in this exact situation and were unable to repair the nose-hull damage and were forced to reload a save to escape.

**Comment by Cptcuddlybuns** [comment]
I can confirm that the Humpback has unrepairable sections at the nose, I've been squashed by the humpback several times and it's always a struggle to get the thing off of you.

**Comment by tsteiner** [comment]
Another confirmation of unrepairable nose segments.
![unfixable hole](https://user-images.githubusercontent.com/195772/199141236-d4267a89-5546-445d-8a54-5a7af2fbe662.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/146b40ee9cb448e5f507129ef41574c822a23342

**Comment by CurePindal** [comment]
> Fixed in https://github.com/Regalis11/Barotrauma-development/commit/146b40ee9cb448e5f507129ef41574c822a23342
> 
> > A safeguard against getting pinned under a pirate sub: if your sub is under an enemy sub with no living enemies inside it, and heading upwards, we gradually "lighten" the submarine on top (i.e. applying artificial buoyancy to it). The sub becomes buoyant in ~30 seconds, and gradually returns to normal in the spawn of 300 seconds once it's no longer being pushed up.

Doesnt seem to work as described here in 1.0.7. 
Yesterday we  had 2 enemy subs stuck to our sub and it was incredibly annoying to get them separated again.
We had to manually fix, de-water and try to lift a Dudong, but even when both subs where technically able to move as if undamaged they wouldnt just separate easily as one would expect.

Still broken. Fix plz. Makes Pirate missions a pain in any crews rear side.

**Comment by Regalis11** [comment]
The fix is not included in the v1.0.7.0 build, but coming in a future patch.

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.
