### ISSUE TITLE
Bots dont fire in railgun

### ISSUE THREAD

**Issue by Chaos456456** [Regalis11/Barotrauma#946]
In singleplayer when I order the bot to get up for a gun and shoot, he gets up for a gun but does not shoot

**Comment by Regalis11** [comment]
This could happen if the bot can't find ammunition for the railgun, if something's preventing the supercapacitors from being charged, or if there's no enemies in sight. What kind of situation did this happen in and which submarine were you using? Are you sure the railgun was ready to fire and there was an enemy within shooting range?

**Comment by Chaos456456** [comment]
This situatin i found in Aegir Mark 3, my railgun had ammo, monster swim near railgan, but bot not fire

**Comment by Chaos456456** [comment]
Sory for mistakes, im not good in English(Im russian).

**Comment by mrjpjr** [comment]
I think this issue might have returned. 

**Description**
Bots are not shooting when assigned to a gun in single player campaign. 
Ammo was loaded, super capacitor was fully charged and there were no obstructions. 
This occurred for 3 rounds back to back to back.

**Steps to Reproduce**
- Start Single Player Campaign
- Assign bot to gun
- Bot does not shoot when creature approaches

**Version**
0.9.9.0 revision 0534150c8 (unstable)
Windows 10

**Additional Information**
I also noticed bots assigned to repair leaks were welding doors shut on more than one occasion (only during 1 round). I don't know is this behaviour is related of not, but I am mentioning it just in case.

**Comment by YeOldeEBM** [comment]
Chiming in to confirm the above post as far as guns are concerned. Bots on coil guns (didn't check railguns) won't fire regardless of bot or gun despite clear lines of fire to targets. This is in a fresh new campaign with no sub damage.

I've not witnessed bots trying to weld doors shut, but they do seem to get stuck randomly when set to repair systems. In one round with a Kastrull two of them were stuck in the gun drone running in circles, not repairing the damaged drone systems. When I ordered one of them to power the reactor, he wouldn't leave the drone, claiming there was no way to the reactor. While there was some lingering damage to various systems, there were no causes I could find that prevented reactor access.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9fe9eee

**Comment by Rokvach** [comment]
Tested bots and they are working as usual now, will have to look at Thalamus as well to see if it affected its behavior in anyway

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Ghostwish-debug** [comment]
This issue is back, but as I've been told, a hotfix is enroute.
