### ISSUE TITLE
Supercapacitor - When creating the device, the charge speed is 1%

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9502]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Supercapasitor - charge speed 1% by default (in the editor).

https://user-images.githubusercontent.com/93348499/176881331-3451562a-9b91-44b3-a5da-202b96d8ba29.mp4

### Reproduction steps

1. Start editor
2. Create `Supercapacitor`
3. RMB - Open 
4. Charge speed = 1%

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6fc1957de02c399e36acf079c563228917d87302

**Comment by NilanthAnimosus** [comment]
Tested in 0.19.0.0

supercapacitor now appears to start with 0% recharge rate by default, which does fix seeing an odd percent for that now.

It seems submarine and shuttle batteries have this issue too though and is not fixed for them. They start with a default recharge rate of 10 which is around 2% of their default recharge rate? yet given you can only change it by 10% increments

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/674dee7c823087234bd41347c21d8da32383ef01

**Comment by Rokvach** [comment]
Tested both batteries and they start at 0% now, working correctly. Closing.
