### ISSUE TITLE
Automatic disconnecting/re-connecting isn't working in ingame hosted servers

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9872]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

While testing networking issues in dev we found out that if the server shuts down the clients left in that server aren't shown any prompt about the server shutting down, so they are just left in the server as if nothing happened.

### Bug prevalence

Happens every time I play

### Version

0.19.5.0 (unstable)

### -

Dev branch, commit: https://github.com/Regalis11/Barotrauma-development/commit/d206ec490f7210e2731599fac655a232d893b804

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Couldn't reproduce. Steps to repro pls? SteamP2P or dedicated? How was the server shut down?

![image](https://user-images.githubusercontent.com/14351070/190972981-4d94b98c-ea6f-4c20-a393-2fbbec9ed4e4.png)

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/6ae69e489819b5f5552a48c86c5f6c35dcc29bc9

**Comment by Rokvach** [comment]
Ingame hosting reconnecting doesn't seem to be working at all, you just get the following error on client side when you get booted out of the server

> Error during connection initialization: completed initialization before receiving content package order.

We also got some varying results while reproing this issue, the first time we tested reconnecting it showed a Steam authentication failed prompt on my end while Nilanth still saw me as connected to the server and whenever I tried to connect back I just kept getting the same error as above with a connection failed prompt, normally you just get booted out with the error message and can join back in, but that one time it just didn't let me.

**Comment by Regalis11** [comment]
Attempted to fix this in https://github.com/Regalis11/Barotrauma-development/commit/10eb9f7734c955f794f591dbf265336bab437a98

**Comment by NilanthAnimosus** [comment]
Tested against dev commit https://github.com/Regalis11/Barotrauma-development/commit/64eda67c652713c36b187768e59f29942a3fa0e2

Issues seem unchanged from previous test with the exception that we did not get a "Steam authentication failed".

still seeing:
```
Error during connection initialization: completed initialization before receiving content package order.
```

From the servers perspective, it appears they remain connected for almost 2 minutes (Perhaps reset by attempted connection? not sure) racking up events not sent and while connected they cannot rejoin due to receiving the same error. Once they have disconnected from the server they may then rejoin without getting the error.

**Comment by Regalis11** [comment]
Another attempt https://github.com/Regalis11/Barotrauma-development/commit/ca818a855558f28bdcb56f76ff343d6dcf864c22

**Comment by Rokvach** [comment]
We tested this in P2P server now

Character does reconnect but you will be out of sync in various different ways until you respawn. 

1. If another player gives you an item they can't see you picking it up and using it, Nilanth gave me a stun baton to hit him with it and on hes end I didn't even pick the stun baton. Only after I picked up a plasma cutter from a nearby cabinet and equipped it, Nilanth was able to see me using the Stun Baton just fine. 
2. You can't hear other players talking on the server but they can hear you talking, this only gets fixed if you respawn, trying to remove headset or spawn a new headset etc didn't fix this. 

You can only reconnect once per round
If you reconnect more than once you will be so out of sync that it will just try to reconnect you again and then you will be stuck on reconnecting fovered. If the server has a password it will ask you to input your password the second time it tries to reconnect you and then it will just disconnect you from the server as connection lost rather than keep you reconnecting endlessly. 

This is what the host sees if you try to reconnect more than once
![image](https://user-images.githubusercontent.com/7299826/193225477-95c4cd9f-e745-45bc-837b-695a1cc60391.png)

**Comment by Rokvach** [comment]
Updated above comment

**Comment by Rokvach** [comment]
Reconnecting works fine now but the character desync issue still persists, I switched to a debug build and noticed whenever I reconnected and Nilanth tried to say something using VOIP my console was spammed with this, we also noticed that you can use setclientcharacter and VOIP starts to work again. 

![image](https://user-images.githubusercontent.com/7299826/193281758-2e051a4c-074a-44bb-8762-61c690124cb6.png)

We also noticed that using the ForceTimeout command has the same outcome as just pausing the server which is the desync issues.

**Comment by Rokvach** [comment]
Tested, the issues we spotted has been fixed, no desync issues anymore. Working correctly so can be merged.
